{% set name = "calamari_ocr" %}
{% set version = "2.1.4" %}
{% set sha256 = "04a78dce69aa58b4dbc5ee9e8de52d3564c249c46c1e779f15a2810be9496ae0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - calamari-eval=calamari_ocr.scripts.eval:main
    - calamari-predict=calamari_ocr.scripts.predict:main
    - calamari-resume-training=calamari_ocr.scripts.resume_training:main
    - calamari-train=calamari_ocr.scripts.train:main
    - calamari-cross-fold-train=calamari_ocr.scripts.cross_fold_train:main
    - calamari-pred_to_json=calamari_ocr.scripts.cross_fold_train:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tensorflow
    - numpy
    - tqdm
    - scikit-image
    - python-bidi
    - edit_distance

test:
  imports:
    - calamari_ocr
    - calamari_ocr.ocr
    - calamari_ocr.ocr.augmentation
    - calamari_ocr.ocr.backends
    - calamari_ocr.ocr.backends.ctc_decoder
    - calamari_ocr.ocr.backends.tensorflow_backend
    - calamari_ocr.ocr.data_processing
    - calamari_ocr.ocr.text_processing
    - calamari_ocr.ocr.voting
    - calamari_ocr.proto
    - calamari_ocr.scripts
    - calamari_ocr.test
    - calamari_ocr.thirdparty
    - calamari_ocr.thirdparty.ocrodeg
    - calamari_ocr.utils
  commands:
    - calamari-eval --help
    - calamari-predict --help
    - calamari-resume-training --help
    - calamari-train --help
    - calamari-cross-fold-train --help
    - calamari-pred_to_json --help

about:
  home: https://github.com/ChWick/calamari
  license: GPL-3.0
  license_family: GPL3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: OCR Engine based on OCRopy and Kraken based on python3.
  description: |
    OCR Engine based on OCRopy and Kraken based on python3. It is designed 
    to both be easy to use from the command line but also be modular to 
    be integrated and customized from other python scripts.
  doc_url: https://github.com/ChWick/calamari
  dev_url: https://github.com/ChWick/calamari

extra:
  recipe-maintainers:
    - CurtLH
