travis:
  secure:
    BINSTAR_TOKEN: ZtqIMT4N9L3w1V8US430oypxn3yKzp3mh6J17TK32zLS4LJT+m6/jlV7JH7PEilw1tLoOsRx45F2T4hiHnlEEVnMZF2moRlyoF/Lz0WP2zUenYV9Nni2dV4NwUZ48TduH3TDdL8wiLbGOeaNuW1Bm514IUSv0wO/aDnC/9iiA+Dl6A3gPetjDr5e0L9qe0iJNgJdRe+ZKFbX5t+4B4LGFOjhgeH+HpA604HhnM5JvsVGldUKyDNDvRpvp2jZHG5nTJs4kic/TpCglqP5pqL5JjnAnO57P2z+/khJz2JSr28PoFIfb5u0ky+PCjgjP7RZocpluKGJtZekPT1mJeT4JAcDJbZ+UxsUcnGnO6NfTJTqGE5Ytz42KM7xIE2iQaYJdOqYohb5lkbsHaMvZairj35iAEDqN8lKLEHEJ3aRcj556XeT+5MeNxc8hCQsfefp9inXIb/mIfw011rHphpPmcr8emOK3y5oax66vFooAyQ5NcB+bBODg3rv82AjPGI0YzCw5AitMNidqiOj5j4Yo7PYlp6xOrGlnEH/JnPrpcN6GnMSRwiI993RGlvztPgx4NO1glOrFGRFbydqpvaZi2CnUEg3O9rN3iHDIfB+1Pe4MAQ4pzDklr8dFl4J5kPthr41oipXCfonIfHgLvpvwdE+/L+i7Qe3N9ZyQ7cNbac=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
